openedx/edx-app-test

README.md, common/strings.py, conftest.py, pages/login.py, pages/main_dashboard.py, pages/new_logistration.py, pages/whats_new.py, testdata/input_data.py, tests/conftest.py, tests/test_login.py, tests/test_new_logistration.py
iOS - Automate New Logistration screen
- Remove AUT(application for tests) 
- Remove user credentials(from InputData) and ask user to add these manually - we'll replace these with parameters soon 
- LEARNER-3792
=> Learner-3792 iOS - Automate New Logistration screen

README.md
- simplified steps
- github flavored changes
=> ReadMe Changes 

android/pages/android_login.py, android/pages/android_main_dashboard.py, android/pages/android_new_logistration.py, android/pages/android_whats_new.py, android/tests/test_android_login.py, android/tests/test_android_main_dashborad.py, android/tests/test_android_new_logistration.py, android/tests/test_android_whats_new.py, common/globals.py, common/strings.py, conftest.py, ios/pages/ios_elements.py, ios/pages/ios_login.py, ios/pages/ios_main_dashboard.py, ios/pages/ios_whats_new.py, ios/tests/test_ios_login.py, ios/tests/test_ios_main_dashboard.py, ios/tests/test_ios_new_logistration.py, ios/tests/test_ios_whats_new.py
- implemented new ids set by iOS dev(LEARNER-3888) on Login Screen
- implemented new ids set by iOS dev(LEARNER-3888) on Whats New Screen
- replaced sleeps with explicit wait where ever possible
=> LEARNER-4119 - iOS - Verify 'Accessibility ID' is properly set against each element - for Login & Whats New Screens

README.md, android/pages/android_base_page.py, android/pages/android_elements.py, android/pages/android_login.py, android/pages/android_main_dashboard.py, android/pages/android_new_logistration.py, android/pages/android_whats_new.py, android/tests/test_android_login.py, android/tests/test_android_main_dashborad.py, android/tests/test_android_new_logistration.py, android/tests/test_android_whats_new.py, common/globals.py, conftest.py, ios/pages/ios_base_page.py, ios/pages/ios_elements.py, ios/pages/ios_login.py, ios/pages/ios_main_dashboard.py, ios/pages/ios_new_logistration.py, ios/tests/test_ios_login.py, ios/tests/test_ios_main_dashboard.py, ios/tests/test_ios_new_logistration.py, ios/tests/test_ios_whats_new.py
* Implemented a wait_for_android_activity_to_load() function
* all element locations have proper locators based on given ids
=> LEARNER-4122 Android - Verify 'Accessibility ID' is properly set against each element - for New Logistration Screen

android/pages/android_base_page.py, android/pages/android_login.py, common/globals.py, common/strings.py
LEARNER-4122 Android - Verify 'Accessibility ID' is properly set against each element - for Login Screen
* all element locations have proper locators based on given ids except Screen Titles and Back icon
=> LEARNER-4122 Android - Verify 'Accessibility ID' is properly set against each element - for Login Screen

android/pages/android_login.py, android/pages/android_main_dashboard.py, android/pages/android_whats_new.py, android/tests/test_android_login.py, android/tests/test_android_whats_new.py, common/globals.py, common/strings.py, ios/pages/ios_elements.py, ios/pages/ios_login.py, ios/tests/test_ios_main_dashboard.py
* Verify that Whats New screen has following contents,
** "Version New Features" as heading
** Cross-icon
** Gallery of the New features, having following contents in each page,
*** New Feature's Icon
*** New Feature's Title
*** New Feature's Details
*** "Done" button at end
* Verify that following values/strings/labels are correct,
** App Version
** Feature Name/Title
** Feature Details
* Verify that on tapping cross-icon will load Main Dashboard screen
* Verify user should be able to navigate between features
* Verify on tapping "Done" will load Main Dashboard screen
* Verify after re-login with same user "Whats New" screen will not be visible
=> LEARNER-3972 Test - Android - Automate Whats New Screen

android/pages/android_elements.py, android/pages/android_new_landing.py, android/pages/android_new_logistration.py, android/tests/test_android_new_landing.py, common/globals.py, common/strings.py, ios/pages/ios_new_landing.py, ios/tests/test_ios_new_landing.py
Following scenarios are covered,
* Verify that Landing screen is loaded successfully
* Verify that Landing screen has following contents,
** edX logo
** Description text-field
** Search Courses edit-field
** Register button
** Sign In button
* Verify that all elements have their default values
* Verify that tapping "Log In" loads Log In screen
* Verify that tapping back icon from "Log In" screen navigate user back to Landing screen
* Verify that tapping "Create Your Account" loads Register screen
* Verify that tapping back icon from "Register" screen navigate user back to Landing screen
* Verify that tapping search after entering <course name> should load "Discovery" screen
* Verify that Discovery screen is showing
* Verify tapping back icon from 'Discovery' screen navigate user back to …
=> LEARNER-4694 Test - Android - Automate new Landing Screen

android/pages/android_login.py, android/pages/android_register.py, android/tests/test_android_main_dashborad.py, common/strings.py, conftest.py, ios/pages/ios_base_page.py, ios/pages/ios_login.py, ios/tests/test_ios_login.py, ios/tests/test_ios_main_dashboard.py, ios/tests/test_ios_new_logistration.py, ios/tests/test_ios_whats_new.py
Replaced New Landing screen in following Test Clases
* Login
* Whats New
* Main Dashboard
* Conftest
=> LEARNER-5044 Test - iOS - replace New Logistration Screen with New Landing screen as default landing screen

android/tests/test_android_whats_new.py, common/strings.py
* Test case will check availability of all contents
* Strings matching/comparison has been removed for followings,
** Screen Title showing App Version
** Feature Title
** Feature Details
=> LEARNER-5614 Test - Android - Whats New screen - remove strings comparison to match Version & Feature Details

common/globals.py, common/strings.py, conftest.py, ios/pages/ios_elements.py, ios/tests/test_ios_login.py, ios/tests/test_ios_whats_new.py
* Test case will check availability of all contents
* Strings matching/comparison has been removed for followings,
** Screen Title showing App Version
** Feature Title
** Feature Details
=> LEARNER-5615 Test - iOS - Whats New screen - remove strings comparison to match Version & Feature Details

.gitignore, package-lock.json, package.json, requirements.txt
LEARNER-7121
Test - add `package.json' file to install dependencies which will support CD infrastructure
=> LEARNER-7121 Test - add `package.json' file to install dependencies which will support CD infrastructure

.gitignore, README.md, common/globals.py, requirements.txt, user_preferences_sample.yml
Following changes have been made, 
* Replace users configuration from system level environment variables to yml file 
* Update gitignore to ignore user_preferences file 
* Add user_preferences_sample.yml file 
* Update requirements.txt file to add yaml support 
* update readme to explain setting user configurations through yml file
=> LEARNER-7275 Test - Restructure edx-app-test project according to AWS Device Form Needs

requirements.txt
Update version of pytest-html library.
=> update pytest-html version

tests/common/globals.py, tests/conftest.py
Following has been implemented 
- capture screenshot on error, screenshot name will be the name of specific test case 
- integrate screenshot into HTML report against specific failed test case
=> LEARNER-3865  Setup to capture device(iOS/Android) screenshot on errors/problems

tests/common/globals.py
[LEARNER-7951](https://openedx.atlassian.net/browse/LEARNER-7951)
- Pass login Credentials from Jenkins to AWS device farm
- Get login Credentials in AWS and set them as environment variables
=> Get Jenkins Credentials

edx-setup-virtual-env.sh, edx-trigger-execution.sh
**Purpose**
Automate test execution process, which will, 
- setup virtual environment 
- trigger execution in needed sequence
=> Automate test execution process

.github/workflows/ci.yml
[LEARNER-8451](https://openedx.atlassian.net/browse/LEARNER-8451)
Github actions job will run on every pull request, and on push request of master branch only.
=> update request name to push in workflow

tests/android/pages/android_course_subsection.py, tests/android/pages/android_elements.py, tests/android/tests/test_android_course_html_component.py, tests/android/tests/test_android_course_resources.py, tests/android/tests/test_android_course_subsection.py, tests/common/globals.py
[LEARNER-8441](https://openedx.atlassian.net/browse/LEARNER-8441)
Verify that the Course Resources tab will show the following contents:
Header contents,
Back icon,
Resources as Title, Share icon,
Verify that the user should be able to go back by clicking the Back icon
Verify that the user should be able to view:
Handouts as Row title
The subtitle of the row,
Handouts icon in a row,
Handouts can be clickable and it will navigate to the handouts page
Handouts as Title of the page
Verify that the user should be able to view:
Announcements as Row title
The subtitle of the row,
Announcements icon in a row,
Announcements can be clickable and it will navigate to the Announcements page
Announcements as Title of the page
=> Automate Resources screen

tests/ios/pages/ios_course_html_component.py, tests/ios/tests/test_ios_course_html_component.py
[LEARNER-7790](https://openedx.atlassian.net/browse/LEARNER-7790)
Automate iOS Course HTML component screen
Verify that the Course Html Component screen will show the following Header contents,
Back icon
Specific "<Topic name>" as Title
Verify that the user should be able to go back by clicking the Back icon
Verify that the user should be able to view these:
Topic name
Verify that footer should have Previous and Next buttons in it
Verify that the user should be able to navigate between the Previous and Next Button from the footer
=> feat: Automate ios course html component screen

tests/common/strings.py, tests/ios/pages/ios_elements.py, tests/ios/pages/ios_profile.py, tests/ios/tests/test_ios_profile.py
[LEARNER-8479](https://openedx.atlassian.net/browse/LEARNER-8479)
Followings features/stories will be implemented:
User Profile screen should be loaded successfully with the following contents,
Avatar
Username
Language
Country
About me
Verify that clicking the back icon on the profile screen should navigate to the Profile options screen	
Verify that the profile screen should have the following header contents: 
back icon
profile
Edit profile
Verify that clicking the back icon on the edit profile screen should navigate to the profile screen
=> Automate Profile screen

tests/ios/pages/ios_main_dashboard.py, tests/ios/pages/ios_my_courses_list.py, tests/ios/pages/ios_register.py, tests/ios/tests/test_ios_course_dashboard.py, tests/ios/tests/test_ios_course_html_component.py, tests/ios/tests/test_ios_course_resources.py, tests/ios/tests/test_ios_course_subsection.py, tests/ios/tests/test_ios_discussions_dashboard.py, tests/ios/tests/test_ios_login.py, tests/ios/tests/test_ios_main_dashboard.py, tests/ios/tests/test_ios_my_courses_list.py, tests/ios/tests/test_ios_register.py, tests/ios/tests/test_ios_video_subsection.py, tests/ios/tests/test_ios_videos_dashboard.py
[LEARNER-8654](https://openedx.atlassian.net/browse/LEARNER-8654)
Description
Update cases for Navigate to Logout from the app
Update all screens that have logout test cases
Update cases for Navigate to the profile screen
Update cases for register screen (YOB)
=> Update iOS automation test cases after release 3.0.0

README.md, tests/common/strings.py, tests/ios/pages/ios_course_dashboard.py, tests/ios/pages/ios_course_subsection.py, tests/ios/pages/ios_elements.py, tests/ios/pages/ios_login.py, tests/ios/pages/ios_login_smoke.py, tests/ios/pages/ios_profile.py, tests/ios/tests/test_ios_course_dashboard.py, tests/ios/tests/test_ios_course_discovery.py, tests/ios/tests/test_ios_course_html_component.py, tests/ios/tests/test_ios_course_resources.py, tests/ios/tests/test_ios_course_subsection.py, tests/ios/tests/test_ios_discussions_dashboard.py, tests/ios/tests/test_ios_edit_profile.py, tests/ios/tests/test_ios_login.py, tests/ios/tests/test_ios_main_dashboard.py, tests/ios/tests/test_ios_my_courses_list.py, tests/ios/tests/test_ios_profile.py, tests/ios/tests/test_ios_profile_options.py, tests/ios/tests/test_ios_register.py, tests/ios/tests/test_ios_video_subsection.py, tests/ios/tests/test_ios_videos_dashboard.py, tests/ios/tests/test_ios_whats_new.py
[LEARNER-8696](https://openedx.atlassian.net/browse/LEARNER-8696)
- create a new login smoke page for login and whats-new test cases and inherit all test files with it
- remove login and whats-new test case from all files
- fix failed test cases
=> Remove code repetition of login and whats-new test cases for iOS

tests/ios/tests/test_ios_course_dashboard.py, tests/ios/tests/test_ios_course_discovery.py, tests/ios/tests/test_ios_course_html_component.py, tests/ios/tests/test_ios_course_resources.py, tests/ios/tests/test_ios_course_subsection.py, tests/ios/tests/test_ios_discussions_dashboard.py, tests/ios/tests/test_ios_edit_profile.py, tests/ios/tests/test_ios_main_dashboard.py, tests/ios/tests/test_ios_profile.py, tests/ios/tests/test_ios_profile_options.py, tests/ios/tests/test_ios_register.py, tests/ios/tests/test_ios_video_subsection.py, tests/ios/tests/test_ios_videos_dashboard.py
https://openedx.atlassian.net/browse/LEARNER-8726
- split big test methods into multiple methods
- split logout test cases to separate test methods
=> feat: split big test methods into multiple methods for ios

tests/android/pages/android_elements.py, tests/android/pages/android_video_dashboard.py, tests/android/tests/test_android_video_subsection.py
[LEARNER-8791](https://openedx.atlassian.net/browse/LEARNER-8791)
Update Native Download videos test cases with updated id's for Android
=> update download videos test cases with updated id's

tests/android/pages/android_elements.py, tests/android/tests/test_android_course_dates.py, tests/common/strings.py
[LEARNER-8818](https://2u-internal.atlassian.net/browse/LEARNER-8818)
Followings features/stories will be implemented:
Verify that Course Dates screen will show following contents,
Header contents,
Back icon,
"Important Dates" as Title Date
Share icon to share specific date
Information about specific dates,
Verify that user should be able to view these contents:
Dates banner title,
Dates banner information
Dates sync title
Dates sync information
Dates start date
Dates start title
Verify all screen contents have their default values
Verify that user should be able to scroll from top to bottom of dates screen
Verify that user should be able to scroll from bottom to top of dates screen
Verify that user can logout from course Dates screen
=> feat: automate dates screen for android

tests/android/pages/android_elements.py, tests/android/pages/android_login.py, tests/android/pages/android_new_landing.py, tests/android/pages/android_register.py, tests/android/tests/test_android_course_dates.py, tests/android/tests/test_android_course_resources.py, tests/android/tests/test_android_login.py, tests/android/tests/test_android_new_landing.py, tests/android/tests/test_android_register.py, tests/common/strings.py
[LEARNER-8939](https://2u-internal.atlassian.net/browse/LEARNER-8939)
Automate missing test cases for these screens:
Login 
New Landing
Register
Course dates
Course resources
Update strings and android-elements file accordingly
=> feat: automate missing test cases for android screens

README.md, tests/android/tests/test_android_login.py, tests/common/globals.py, tests/conftest.py
[LEARNER-9063](https://2u-internal.atlassian.net/browse/LEARNER-9063)
Remove Jenkins code from the test repo after Jenkins shutdown
=> refactor: Remove jenkins code

tests/common/strings.py, tests/ios/pages/ios_elements.py, tests/ios/pages/ios_login.py, tests/ios/pages/ios_new_landing.py, tests/ios/pages/ios_profile.py, tests/ios/tests/test_ios_login.py, tests/ios/tests/test_ios_new_landing.py, tests/ios/tests/test_ios_profile.py, tests/ios/tests/test_ios_register.py
[LEARNER-8940](https://2u-internal.atlassian.net/browse/LEARNER-8940)
Automate missing test cases for these screens:
Login
New Landing
Register
Profile
Update strings and android-elements file accordingly
=> feat: update missing test cases for ios screens

tests/common/globals.py, tests/conftest.py
[LEARNER-9234](https://2u-internal.atlassian.net/browse/LEARNER-9234)
- Add required capabilities to run on Github actions.
- Add emulator and OS version details of Github actions in test repo so that the emulator can run automation test cases on it.
- Make configurations separate from running the test cases locally.
=> chore: add configurations to run on github actions workflows

requirements.txt, tests/common/globals.py, tests/conftest.py
[LEARNER-8960](https://2u-internal.atlassian.net/browse/LEARNER-8960)
- Get credentials for enable_workflows condition
- set whats new to False because current android release has no whats new in it.
- Update libraries to run on Github Actions runner
=> chore: get credentials from github actions workflow and logins the app

tests/android/pages/android_elements.py, tests/android/pages/android_main_dashboard.py, tests/android/tests/test_android_course_dashboard.py, tests/android/tests/test_android_course_resources.py, tests/android/tests/test_android_discussions_dashboard.py, tests/android/tests/test_android_videos_dashboard.py
[LEARNER-9395](https://2u-internal.atlassian.net/browse/LEARNER-9395)
Description
Update all test cases from videos dashboard screen according to new app nav design
=> chore: automate video tab  for app nav design

tests/android/tests/test_android_course_dates.py, tests/android/tests/test_android_discussion_details.py, tests/android/tests/test_android_profile_options.py, tests/common/strings.py
[LEARNER-9506](https://2u-internal.atlassian.net/browse/LEARNER-9506)
Fix failed test cases after Android release 4.1.1.
The following screens will be updated in this:
- Dates 
- Discussions
- Profile options
=> fix: failed test cases after android release 4.1.1
